<a href="https://colab.research.google.com/github/Nguyenhunggiabao/ThucHanhToanCC/blob/main/DSTT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nguyễn Hùng Gia Bảo

CHƯƠNG 2: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN TÍNH

1. Dẫn nhập – Một số hàm về xử lý vector với Python 

Hàm “scale” tỉ số vector bằng một giá trị thực:

In [1]:
def scale(a, v):
 return [a*vi for vi in v]
v = [3,5,7]
scale(10, v) 

[30, 50, 70]

Hàm lấy tổng hai vector:

In [2]:
def sumvector(v, w):
 return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
sumvector(v, w) 

[5, 9, 13]

Hàm nhân 2 vector vô hướng:

In [3]:
def dotvector(v, w):
 return sum([vi*wi for (vi, wi) in zip(v, w)])
dotvector(v, w)

68

Hàm tính chiều dài một vector:

In [4]:
def lenvector(v):
 return dotvector(v,v)
lenvector(w) 

56

2. Bài toán ứng dụng 1 – Phân loại tuyến tính

In [6]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4]) 
scores >= 0 
scores < 0 
np.select([scores >=0, scores < 0],['so duong', 'so am']) 

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [7]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'])

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

3.1. Cơ bản về xử lý ma trận

In [8]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6, 2*x*x-8, z*z+4-5, y-z-8], [x,y,z])

[(-2, 7, -1), (2, 7, -1)]

In [9]:
import numpy as np 
np.array_equal([1,2],[1,2])

True

In [10]:
np.array_equal(np.array([1,2]), np.array([1,2]))

True

3.2. Các phép biến đổi sơ cấp trên ma trận 

In [11]:
import numpy as np 
A = np.reshape(np.arange(36.0), (6,6))
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [13]:
I6 = np.identity(6)
print (I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [14]:
A.size 

36

In [15]:
np.matrix.diagonal(A) 

array([ 0.,  7., 14., 21., 28., 35.])

In [17]:
A = A + I6
print(A)

[[ 2.  1.  2.  3.  4.  5.]
 [ 6.  9.  8.  9. 10. 11.]
 [12. 13. 16. 15. 16. 17.]
 [18. 19. 20. 23. 22. 23.]
 [24. 25. 26. 27. 30. 29.]
 [30. 31. 32. 33. 34. 37.]]


In [19]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)

[ 72. 200. 328. 456. 584. 712.]


Khai báo ma trận D 2x6 

In [20]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


Xây dựng ma trận F kích thước 6x2: 



In [24]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print(F)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]


In [26]:
print(G)

[[ 72.   8.]
 [200.  24.]
 [328.  44.]
 [456.  60.]
 [584.  80.]
 [712.  96.]]


Tính ma trận nghịch đảo: 

In [28]:
np.linalg.inv(A) 

array([[ 0.10336538, -0.28605769, -0.17548077, -0.06490385,  0.04567308,
         0.15625   ],
       [-0.27403846,  0.29326923, -0.13942308, -0.07211538, -0.00480769,
         0.0625    ],
       [-0.15144231, -0.12740385,  0.39663462, -0.07932692, -0.05528846,
        -0.03125   ],
       [-0.02884615, -0.04807692, -0.06730769,  0.41346154, -0.10576923,
        -0.125     ],
       [ 0.09375   ,  0.03125   , -0.03125   , -0.09375   ,  0.34375   ,
        -0.21875   ],
       [ 0.21634615,  0.11057692,  0.00480769, -0.10096154, -0.20673077,
         0.1875    ]])

In [29]:
np.linalg.inv(np.linalg.inv(A))

array([[ 2.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  9.,  8.,  9., 10., 11.],
       [12., 13., 16., 15., 16., 17.],
       [18., 19., 20., 23., 22., 23.],
       [24., 25., 26., 27., 30., 29.],
       [30., 31., 32., 33., 34., 37.]])

4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng! 

In [30]:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10
for i in range(n):
 b = A.dot(b)
 print(b) 

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


5.2. Bài toán ứng dụng 3 – Đếm số lượng xe vào khu vực trung tâm 

In [31]:
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
nghiem

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

In [40]:
import numpy as np
a = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]]) 
