<a href="https://colab.research.google.com/github/Nguyenhunggiabao/ThucHanhToanCC/blob/main/DSTT6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nguyễn Hùng Gia Bảo 

CHƯƠNG 6: CÁC KHÁI NIỆM: KHÔNG GIAN VECTOR, TÍCH TRONG VÀ TRỊ RIÊNG, VECTOR
RIÊNG

Khái niệm về không gian vector và tích trong

In [16]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print (tich) 

32


In [17]:
np.dot(a,b)

32

In [18]:
import numpy as np
a = np.array([1,2,-3])
np.linalg.norm(a)

3.7416573867739413

In [19]:
a = np.array([1,2,-3])
np.linalg.norm(a,1) 

6.0

In [20]:
import math
def chuan (v,k):
  tong = 0 
  for i in range(len(v)):
    tong = tong + abs(v[i]**k)
  ketqua = math.pow(tong,1.0/k)
  return ketqua

In [21]:
import numpy as np
a = np.array([1,2,-3])
chuan(a, 1)

6.0

In [22]:
np.linalg.norm(a,1)

6.0

In [23]:
chuan(a, 2)

3.7416573867739413

In [24]:
np.linalg.norm(a,2)

3.7416573867739413

In [25]:
chuan(a, 3) 

3.3019272488946263

In [26]:
np.linalg.norm(a,3)

3.3019272488946263

In [27]:
chuan(a, 1000)

1.0442214818467515

In [29]:
from scipy import linalg
linalg.norm(a) 

3.7416573867739413

In [30]:
linalg.norm(a, 100)

3.0

Tri riêng, vector riêng của ma trận và ứng dụng 

In [32]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y]) 
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem)) 

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [34]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [35]:
print (sympy.pretty(nghiem)) 

[-7, 3]


In [36]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) # tính giá trị nghịch đảo của P
print (P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [37]:
A.dot(P) 

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [38]:
P @ (D ** 1000) @ P1 

array([[ 5.03503397e+18,  3.50482117e+18],
       [ 3.50482117e+18, -4.31115581e+18]])

In [39]:
print (D **2) 

[[49  0]
 [ 0  9]]
