<a href="https://colab.research.google.com/github/Nguyenhunggiabao/ThucHanhToanCC/blob/main/DSTT5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nguyễn Hùng Gia Bảo 

CHƯƠNG 5: ĐỊNH THỨC, MA TRẬN VÀ ỨNG DỤNG

Sử dụng array và matrix trong numpy

In [1]:
from numpy import matlib
G = matlib.identity(5)
print (G)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [2]:
H = matlib.randn(3,2)
print(H)

[[ 0.72419066  0.45673324]
 [-0.79361729  0.02052057]
 [-0.15817859 -0.8589396 ]]


In [3]:
K = matlib.zeros([4,4])
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ứng dụng 2 –Liên phân số và số pi

In [4]:
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2] 
M = np.mat([[1,2],[3,4]]) 
for i in range(len(c)):
 ci = np.mat([[1,1],[1,0]])
 ci[0, 0] = c[i]
 if (i==0):
    M = ci
 else:
    M = M.dot(ci)
print(M)
print (M[0,0]/M[1,0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936
