<a href="https://colab.research.google.com/github/Nguyenhunggiabao/ThucHanhToanCC/blob/main/DSTT3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nguyễn Hùng Gia Bảo 

CHƯƠNG 3: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN TÍNH

1.1. Một số phép xử lý ma trận của NumPy và Scipy 

In [65]:
from scipy import linalg 
import numpy as np 

In [66]:
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
C = np.mat(np.random.random( (10,5) ) )
D = np.mat([ [4, 3], [2, 6] ])
F = np.eye(3, k=1) # tạo ma trận đường chéo. 3 là ma trận 3x3, k=1 là đường chéo nằm phía trên đường chéo chính (k = 0). 

Xem hạng ma trận:

In [67]:
np.linalg.matrix_rank(C)

5

Tính ma trận nghịch đảo: 

In [68]:
A.I 

matrix([[-14.00803422,   7.79447086],
        [  3.48841931,  -0.32154174]])

In [69]:
linalg.inv(A)

array([[-14.00803422,   7.79447086],
       [  3.48841931,  -0.32154174]])

Định thức ma trận: 

In [70]:
linalg.det(A)

-0.044079631821775114

Chuyển đổi ma trận: 

In [71]:
A.T

matrix([[0.01417344, 0.15376824],
        [0.34357741, 0.61746899]])

In [72]:
A.H

matrix([[0.01417344, 0.15376824],
        [0.34357741, 0.61746899]])

Giải các loại phương trình tuyến tính:

In [73]:
linalg.solve(A, b) 

array([[-14.00803422-94.89442451j,   0.        +10.95628587j,
          0.         +4.74272251j],
       [  3.48841931+30.1096068j ,   0.         +5.3691299j ,
          0.         +8.53600746j]])

In [74]:
E = np.mat(a).T

In [75]:
linalg.lstsq(F, E)

(array([[0.],
        [1.],
        [2.]]), array([], dtype=float64), 2, array([1., 1., 0.]))

Cộng ma trận

In [76]:
np.add(A, D)

matrix([[4.01417344, 3.34357741],
        [2.15376824, 6.61746899]])

Trừ ma trận: 

In [77]:
np.subtract(A, D) 

matrix([[-3.98582656, -2.65642259],
        [-1.84623176, -5.38253101]])

Chia ma trận:

In [78]:
np.divide(A, D) 

matrix([[0.00354336, 0.1145258 ],
        [0.07688412, 0.1029115 ]])

Nhân ma trận: 

In [79]:
A @ D

matrix([[0.74384858, 2.10398476],
        [1.85001094, 4.16611866]])

In [80]:
np.multiply(D, A) 

matrix([[0.05669377, 1.03073222],
        [0.30753648, 3.70481394]])

In [81]:
np.dot(A, D) 

matrix([[0.74384858, 2.10398476],
        [1.85001094, 4.16611866]])

In [82]:
np.vdot(A, D) 

matrix([[0.05669377]])

Hàm lũy thừa và logarith ma trận: 

In [83]:
linalg.expm(A) 

array([[1.04752804, 0.48255274],
       [0.21596672, 1.89485361]])

In [84]:
linalg.logm(A)

array([[-2.5130721 +2.8202102j ,  1.0845501 -1.42308485j],
       [ 0.48539094-0.63690233j, -0.60868537+0.32138245j]])

Ma trận phân kỳ: 

In [85]:
import numpy as np
A = np.array([ [0,1], [1,0]])
print(A) 

[[0 1]
 [1 0]]


In [86]:
temp = A.dot(A)
print(temp) 
k= 6
for i in range(k-1):
 temp = temp.dot(A)
 print (temp)
 print('---') 

[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


In [87]:
B = np.array([ [0,-1], [-1,0]])
print(B) 
temp = B.dot(B)
print(temp) 
k= 5
for i in range(k-1):
 temp = temp.dot(B)
 print (temp)
 print('---')

[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


Ma trận hội tụ - Convergent matrix:

In [88]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C) 
temp = C.dot(C)
print(temp)
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp)
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2.4. Ma trận Markov

In [89]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM) 

[[0.7  0.45]
 [0.3  0.55]]


In [90]:
MM = M.dot(M) # tính M3
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [91]:
for i in range(100): # tính các M^ khác.
 MM = MM.dot(M)
print (MM)

[[0.6 0.6]
 [0.4 0.4]]


Bài toán loan tin

In [92]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A)
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [93]:
temp = temp.dot(A)
print(temp)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [94]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
 temp = temp.dot(A)
 sumA = sumA + temp
print (temp)
print (sumA) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
