<a href="https://colab.research.google.com/github/Nguyenhunggiabao/ThucHanhToanCC/blob/main/ktDSTTlan2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nguyễn Hùng Gia Bảo 

kiểm tra giữa kì lần 2 

câu 1 a

In [2]:
import numpy as np
from numpy import linalg as la

w, v = la.eig(np.array([[-1, 2],[3,0]]))
print(w)

[-3.  2.]


câu 1 b 

In [3]:
import numpy as np
from numpy import linalg as la

w, v = la.eig(np.array([[1,-1,0],[-4,1,0],[0,0,3]]))
print(w)

[ 3. -1.  3.]


câu 2 a

In [4]:
import numpy as np
u = np.array([1,0,3])
v = np.array([-2,2,5])
tich = np.inner(u,v)
print (tich)

13


câu 2 b 

In [5]:
import numpy as np
u = np.array([1,0,3])
np.linalg.norm(u)

3.1622776601683795

In [6]:
import numpy as np
v = np.array([-2,2,5])
np.linalg.norm(v)

5.744562646538029

câu 2 c 

In [7]:
import math 
tich = np.inner(u,v)
tichdd = np.linalg.norm(u,1)* np.linalg.norm(v,1)
goc = math.acos(tich/tichdd)
print(goc)

1.2013371968951267


câu 3 

In [12]:
import numpy as np 
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])

In [13]:
x = 2*u-(v+3*w) 
print(x)

[ 18 -11   9  -8]


In [15]:
x= (2*u - v + 2*x + 3*w)/3
print(x)

[ 6. -7.  9. -2.]


câu 4 

In [16]:
from numpy import linalg
A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print (X)  

[ 1. -2. -1.]


câu 6 

In [18]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1 - c2 + c3, 3*c1+2*c2, c1+c2+3*c3], [c1, c2, c3]) 

{c1: 0, c2: 0, c3: 0}

tìm ra chỉ 1 kết quả c nên 3 vector trên độc lập tuyến tính trong hệ R3

câu 5 a

In [22]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1-c3-1, 2*c1+c2-1, 3*c1+2*c2+c3-1], [c1, c2, c3]) 

{c1: c3 + 1, c2: -2*c3 - 1}

vector (1,1,1) là tổ hợp tuyến tính của 3 vector 

câu 5 b 

In [24]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1-c3 -1, 2*c1+c2+2, 3*c1+2*c2+c3-2], [c1, c2, c3]) 

[]

vector (1,-2,2) không là tổ hợp tuyến tính của 3 vector 